### ISSUE TITLE
functions in bl-include-cfg leak local variables

### ISSUE THREAD

**Issue by xaosfiftytwo** [BunsenLabs/bunsen-common#1]
This small test script shows the problem:
`
# !/usr/bin/env bash

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi
safeInstall autoconf
declare
exit 0
`
Output shows ignore_string{1,2,3} leak into the environment.
Solution: Make the variables local to the functions.

@John,
If you want these changes included, I can prepare and test patches.
xaos52

**Comment by johnraff** [comment]
@xaosfiftytwo Thank you for catching that. 
I was wondering about going over all my functions to check for such leaks, but since I always initialize variables before using them the problem would have been for other people, and I was too busy(=lazy) to do it.

I notice the variable "arg" - that also needs localizing I suppose? Would a declaration `local arg` automatically unset any value it might have inherited from the environment without having to explicitly unset it with `unset arg`?

Anyway, if you have the time to fix this a patch will be very welcome.

If you notice any other potential problems or possibilities for improvement in our scripts, feedback will be most appreciated!

**Comment by xaosfiftytwo** [comment]
I must admit that I do not understand what the arg variable is being used for in the apt functions.
If $1 is an option, it is shifted out of $@, nothing else is done with it, it seems, and then in the apt-get command it is added again to the arguments of apt-get.
Unless arg is used in a script that sources bl-include-cfg, and that is the reason why it was not a local variable, but I have not been able to find such a script.
Seems to me the functions can be simplified by just passing all arguments unchanged to apt-get.
Or am I missing something?

**Comment by johnraff** [comment]
$arg is used in the previous function promptInstall() where some checking is done before passing on the option to safeInstall(), and different action taken in one case (--setup). I just carried this practice on in safeInstall() and safeRemove() in case some similar filtering might be needed in the future.

As you say, the way it is now, the transformation $1>$arg in safeInstall() and safeRemove() does nothing in particular and could just be taken out, passing all the arguments on to apt-get as they are.

It's not a bug, though, so I'll do it next time bl-include.cfg is updated (a couple of new functions to be added soon) - unless you'd like to add it to your patch?

**Comment by xaosfiftytwo** [comment]
OK. I will include it or create a separate patch.

What do you  think of this?

`
safeRemove() {
    local ignore_string1='Extracting templates from packages: 100%' # apt sends this to stderr!
    local ignore_string2='Retrieving bug reports... Done' # apt-listbugs sends this to stderr!
    local ignore_string3='Parsing Found/Fixed information... Done' # apt-listbugs sends this to stderr!
    local apt_error
    apt_error=$(LC_MESSAGES=C sudo apt-get remove "${@}" 2>&1 >/dev/tty)
    (( $? == 0 )) && {
        say "Successfully removed ${_}"
        return 0
    } || {
        [[ $apt_error ]] && apt-error=$(grep -iqEv "(${ignore_string1}|${ignore_string2}|${ignore_string3}|^$)" <<<"$apt_error")
        errorExit "There were problems removing ${_}" "${apt_error:-Install Aborted}"
        return 1
    }
}

`

It tests the return code from apt-get
rc 0 means all is A_OK - no further processing needed. No grep needed.
Only if rc != 0 do we execute the grep command on string apt_error.

**Comment by johnraff** [comment]
The reason I was grepping STDERR as well as checking apt-get's return value is that `apt-get update` returns _success_ even if some repositories are missing (and can cause severe system damage if the user goes on to dist-upgrade). Checking STDERR is necessary to detect the problem. With that in mind, I'd rather stay on the conservative side for all the apt-get functions, and check STDERR even if the command returns zero.

For now, let's just localize the ignore strings.

**Comment by xaosfiftytwo** [comment]
OK.
Thanks for the info.
Will do as you suggest.

**Comment by xaosfiftytwo** [comment]
It is possible to do the grep **only when apt_error is not zero**
Which will save a grep call in the majority of all possible cases, and still capture that anomaly you mentioned.
Will prepare a patch for it and test it thoroughly.
Perhaps you have a specific use case for the anomaly? Most probably not because it depends on the actual situation of mirrors being used.

**Comment by johnraff** [comment]
> ...Which will save a grep call...

To be quite honest, I'm really not worried about saving a grep call in this situation. The time required is miniscule by comparison with the time taken by apt-get. 

The specific case when problems arose (which actually happened in the past) was when the CrunchBang server was down for a day or two. Because `apt-get update` returned zero even though some of the sources in sources.list were unavailable, _cb-welcome_ went on to do a `dist-upgrade` which upgraded some packages from CrunchBang versions (which were usually pinned at 1001) to Debian versions. Other packages were deemed "unnecessary" and removed...

In the case of missing repositories, apt-get update outputs a warning in STDERR while returning zero. The first plan was just to check for the existence of stderr, but there are sometime harmless messages there too, hence the need to scan with grep.

If you want to test this, just put a non-existent repository in _sources.list_. Of course the code to test for a non-empty STDERR before running grep would do no harm, but I don't see it as a high priority.
